variable "rds_subnet" {}
variable "engine" {}
variable "engine_version" {}
variable "db_identifier" {}
variable "db_instance_type" {}
variable "db_allocated_storage" {}
variable "db_storage_type" {}
variable "db_username" {}
variable "db_password" {}
variable "db_securitygroup_id" {}